import { SignedIn, SignedOut, SignIn, UserButton } from "@clerk/nextjs";
import Head from "next/head";
import { Header } from "~/components/header";
import { TodoListContainer } from "~/components/todo-list";
import { prisma } from "~/lib/prisma";

export default function Home() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Header />
      <main className="container mx-auto p-4">
        <SignedOut></SignedOut>
        <SignedIn>
          <div className="flex container p-4">
            <TodoListContainer />
          </div>
        </SignedIn>
      </main>
    </>
  );
}
