import { SignedIn } from "@clerk/nextjs";
import Head from "next/head";
import { Header } from "~/components/header";
import { PingsContainer } from "~/components/pings";

export default function Home() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Header />
      <main className="flex flex-col container mx-auto p-4">
        <SignedIn>
          <PingsContainer />
        </SignedIn>
      </main>
    </>
  );
}
